# Generated by Django 4.1 on 2022-10-30 18:13

import django.core.validators
from django.db import migrations, models
import requisicoes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr', models.CharField(max_length=100, unique=True)),
                ('modo', models.CharField(max_length=100)),
                ('tamanho', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('arquivo', models.FileField(upload_to=requisicoes.models.update_filename, validators=[requisicoes.models.file_size, django.core.validators.FileExtensionValidator(['txt', 'ini', 'md', 'json', 'geojson', 'png', 'jpg', 'jpeg', 'odt', 'ods', 'odp', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'pdf', 'zip', 'rar', 'tar', 'gzip', 'gz', '7z'])])),
            ],
            options={
                'db_table': 'anexo',
            },
        ),
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=10, unique=True)),
                ('militar', models.CharField(max_length=100)),
                ('datahora', models.DateTimeField(auto_now_add=True, help_text='Hora da Assinatura')),
                ('pr', models.CharField(max_length=100)),
                ('documento_assinado', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'assinatura',
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('comentario', models.CharField(max_length=200)),
                ('datahora', models.DateTimeField(auto_now_add=True, help_text='Hora da Assinatura')),
            ],
            options={
                'db_table': 'comentario',
            },
        ),
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contas_salc', models.CharField(blank=True, help_text='Contas do SPED autorizadas a executar as ações da <b>SALC</b>', max_length=100, null=True, validators=[django.core.validators.int_list_validator])),
                ('conta_fiscal', models.IntegerField(blank=True, help_text='Conta do SPED autorizada a assinar em <b>Fiscal Administrativo</b>', null=True)),
                ('conta_od', models.IntegerField(blank=True, help_text='Conta do SPED autorizada a assinar em <b>Ordenador de Despesas</b>', null=True)),
                ('conta_odsubstituto', models.IntegerField(blank=True, help_text='Conta do SPED autorizada a assinar como <b>Ordenador de Despesas Substituto</b>', null=True)),
            ],
            options={
                'verbose_name_plural': 'Configurações',
                'db_table': 'configuracao',
            },
        ),
        migrations.CreateModel(
            name='Processo_requisitorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secao_ano_nr', models.CharField(max_length=100, unique=True)),
                ('resumo', models.CharField(max_length=200)),
                ('valido', models.BooleanField(null=True)),
                ('dados', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Processos',
                'db_table': 'processo_requisitorio',
            },
        ),
    ]
