# Generated by Django 4.1 on 2022-10-13 01:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contas_salc', models.CharField(blank=True, help_text='Contas do SPED autorizadas a executar as ações da <b>SALC</b>:', max_length=100, null=True, validators=[django.core.validators.int_list_validator])),
                ('conta_fiscal', models.IntegerField(blank=True, help_text='Conta do SPED autorizada a assinar em <b>Fiscal Administrativo</b>:', null=True)),
                ('conta_od', models.IntegerField(blank=True, help_text='Conta do SPED autorizada a assinar em <b>Ordenador de Despesas</b>:', null=True)),
                ('conta_odsubstituto', models.IntegerField(blank=True, help_text='Conta do SPED autorizada a assinar como <b>Ordenador de Despesas Substituto</b>:', null=True)),
            ],
            options={
                'verbose_name_plural': 'Configurações',
                'db_table': 'configuracao',
            },
        ),
    ]
