# Generated by Django 4.1 on 2022-10-11 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id_pessoa', models.AutoField(primary_key=True, serialize=False)),
                ('nm_login', models.CharField(max_length=50)),
                ('nm_completo', models.CharField(max_length=150)),
                ('cd_patente', models.IntegerField()),
                ('nm_guerra', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Secao',
            fields=[
                ('id_secao', models.AutoField(primary_key=True, serialize=False)),
                ('id_pai', models.IntegerField()),
                ('nm_sigla', models.CharField(max_length=50)),
                ('in_excluido', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nm_usuario', models.CharField(max_length=50)),
                ('in_excluido', models.CharField(max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.CreateModel(
            name='Usuario_Pessoa',
            fields=[
                ('id_usuario_pessoa', models.AutoField(primary_key=True, serialize=False)),
                ('dt_fim', models.CharField(max_length=50)),
                ('id_pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requisicoes.pessoa')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requisicoes.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conta_fiscal', models.ForeignKey(blank=True, help_text='Conta do SPED autorizada a assinar em <b>Fiscal Administrativo</b>:', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiscal', to='requisicoes.usuario')),
                ('conta_od', models.ForeignKey(blank=True, help_text='Conta do SPED autorizada a assinar em <b>Ordenador de Despesas</b>:', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='od', to='requisicoes.usuario')),
                ('conta_odsubstituto', models.ForeignKey(blank=True, help_text='Conta do SPED autorizada a assinar como <b>Ordenador de Despesas Substituto</b>:', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='odsubstituto', to='requisicoes.usuario')),
                ('contas_salc', models.ManyToManyField(blank=True, help_text='Contas do SPED autorizadas a executar as ações da <b>SALC</b>:', null=True, to='requisicoes.usuario')),
            ],
            options={
                'verbose_name_plural': 'Configurações',
            },
        ),
        migrations.CreateModel(
            name='Usuario_Secao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_secao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requisicoes.secao')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requisicoes.usuario')),
            ],
            options={
                'unique_together': {('id_usuario', 'id_secao')},
            },
        ),
    ]
